services:
  database:
    image: 'postgres:latest'
    restart: 'always'
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 15433:80
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  # backend:
  #   image: 'backend'
  #   build:
  #     context: ./dash_backend
  #     dockerfile: ./Dockerfile
  #   env_file:
  #     - .env
  #   depends_on:
  #     - database
  #   ports:
  #     - 8000:8000
  # frontend:
  #   image: 'frontend'
  #   build:
  #     context: ./dash_frontend
  #     dockerfile: ./Dockerfile
  #   env_file:
  #     - .env
  #   ports:
  #     - 5000:5000

volumes:
  db:
    driver: local
  pgadmin-data:
    driver: local 